# This file is generated. Do not modify it directly.
APINames = 
[:JLFreeFromMe, :JLEval, :FetchJLErrorSize, 
 :FetchJLError, :JSymToJV, :JLTypeOf, 
 :JLTypeOfAsTypeSlot, :JLIsInstanceWithTypeSlot, 
 :JLCall, :JLDotCall, :JLCompare, 
 :JLGetProperty, :JLSetProperty, 
 :JLHasProperty, :JLGetIndex, :JLGetIndexI, 
 :JLSetIndex, :JLSetIndexI, :JLGetSymbol, 
 :JLGetBool, :JLGetUInt8, :JLGetUInt32, 
 :JLGetUInt64, :JLGetInt32, :JLGetInt64, 
 :JLGetSingle, :JLGetDouble, :JLGetComplexF64, 
 :JLGetUTF8String, :JLGetArrayPointer, 
 :JSymFromString, :ToJLInt64, :ToJLUInt64, 
 :ToJLUInt32, :ToJLUInt8, :ToJLString, 
 :ToJLBool, :ToJLFloat64, :ToJLComplexF64, 
 :JLStrVecWriteEltWithUTF8, :JLStrVecGetEltNBytes, 
 :JLStrVecReadEltWithUTF8, :JLTypeToIdent, 
 :JLTypeFromIdent, :JLNew_F64Array, 
 :JLNew_U64Array, :JLNew_U32Array, 
 :JLNew_U8Array, :JLNew_I64Array, 
 :JLNew_BoolArray, :JLNew_ComplexF64Array, 
 :JLNew_StringVector, :JLArray_Size, 
 :JLArray_Rank, :JLError_EnableBackTraceMsg, 
 :JLError_HasBackTraceMsg, :JLError_FetchMsgSize, 
 :JLError_FetchMsgStr, :JLCommonTag]
