# This file is generated. Do not modify it directly.
APINames = 
[:JLFreeFromMe, :JLEval, :FetchJLErrorSize, 
 :FetchJLError, :JSymToJV, :JLTypeOf, 
 :JLTypeOfAsTypeSlot, :JLIsInstanceWithTypeSlot, 
 :JLCall, :JLDotCall, :JLCompare, 
 :JLGetProperty, :JLSetProperty, 
 :JLHasProperty, :JLGetIndex, :JLGetIndexI, 
 :JLSetIndex, :JLSetIndexI, :JLGetSymbol, 
 :JLGetBool, :JLGetUInt8, :JLGetUInt16, 
 :JLGetUInt32, :JLGetUInt64, :JLGetInt8, 
 :JLGetInt16, :JLGetInt32, :JLGetInt64, 
 :JLGetSingle, :JLGetDouble, :JLGetComplexF64, 
 :JLGetComplexF32, :JLGetUTF8String, 
 :JLGetArrayPointer, :JSymFromString, 
 :ToJLInt64, :ToJLInt32, :ToJLInt16, 
 :ToJLInt8, :ToJLUInt64, :ToJLUInt32, 
 :ToJLUInt16, :ToJLUInt8, :ToJLString, 
 :ToJLBool, :ToJLFloat64, :ToJLFloat32, 
 :ToJLComplexF64, :ToJLComplexF32, 
 :JLStrVecWriteEltWithUTF8, :JLStrVecGetEltNBytes, 
 :JLStrVecReadEltWithUTF8, :JLTypeToIdent, 
 :JLTypeFromIdent, :JLNew_F64Array, 
 :JLNew_F32Array, :JLNew_U64Array, 
 :JLNew_U32Array, :JLNew_U16Array, 
 :JLNew_U8Array, :JLNew_I64Array, 
 :JLNew_I32Array, :JLNew_I16Array, 
 :JLNew_I8Array, :JLNew_BoolArray, 
 :JLNew_ComplexF64Array, :JLNew_ComplexF32Array, 
 :JLNew_StringVector, :JLArray_Size, 
 :JLArray_Rank, :JLError_EnableBackTraceMsg, 
 :JLError_HasBackTraceMsg, :JLError_FetchMsgSize, 
 :JLError_FetchMsgStr, :JLCommonTag, 
 :JLShareObject]
